export default [
  "Aurorium",
  "Blysstark",
  "Celesteville",
  "Dreamscape",
  "Elysium Heights",
  "Fantasia Bay",
  "Glitterfall",
  "Heavenly Hills",
  "Illuminia",
  "Jewelstone",
  "Kaleidoscape",
  "Luminor",
  "Majestic Heights",
  "Nebula City",
  "Orbital Park",
  "Paradise Point",
  "Quantum Heights",
  "Radiant Ridge",
  "Starfall",
  "Twilight Town"
];
